### PR TITLE
request to add the modded infographics

### PR DESCRIPTION
**Pull request by NajmiAchraf**

### CODE REVIEW

**Comment by jankapunkt** [comment]
Thanks a lot I will review over the weekend and will let you know if anything is missing. Don't worry this looks like it's going a good direction.

**Review by jankapunkt — CHANGES_REQUESTED** [review]
So first of all thank you very much for your pull request. Your solution for the timeline and your other tweaks look very promising. 

However, there are some things that have to be changed, before we can go further here. Let me know, if need help with this.

Legend:

must - no way around this
should - if you have an argument against it, I will hear you out
could - an alterantive you can apply or ignore without comment
would - personal preference with no impact so far

**Must**

- move the .png in your `media` folders to top-level folder `latexcv/docs/media`
- remove main0.pdf and rename maineng.pdf to main.pdf
- rename your tex file in your folders to main.tex
- you must implement

**Should**

- you should add some documentation comments in the .tex files, where new things have been added (this mostly focuses on the graphics like timeline)
- you should use only one graphics folder `g` for both, since both are simply different language implementations and use the very same graphics, right?
- please restructure the folders into:

````
/infographics2
    /en (your English version)
    /fr  (your French  version)
    /g (the graphics folder)
```

**could**

- you can add your name to the authors names in the .tex files

**Comment by NajmiAchraf** [comment]
I have made the important changes requested.

Regarding the timeline documentation, I already made a comment above explaining the roles of each argument.

**Review by NajmiAchraf — COMMENTED** [review]
I have made the important changes requested.

Regarding the timeline documentation, I already made a comment above explaining the roles of each argument.

**Comment by jankapunkt** [comment]
Thank you I will look into it this weekend

**Review by jankapunkt — APPROVED** [review]

**Pull request merged**
